typography_spectrum: 0.9758236855268478
color:
  brandStrength: 0.20112764509394765
  lightness: 0.5720229248981923
  saturation: 0.6026940508745611
  rhythmicContrast: 0.6878348793834448
  brandColors:
    - '#000000'
    - '#333333'
    - '#FF358B'
    - '#01B0F0'
    - '#AEEE00'
layout_spectrum: 0.9448571873363107
author:
  name: Liese Ho
  email: liese.ho@gmail.com
  url: www.happyhappyjoy.com
name: HappyHappyJoy!
navigation:
  - name: Why Happy Happy Joy?
    id: 24156095-b25c-4652-80f2-3d76eedd10ca
    type: content
title: Happy Happy Joy!
description: 'Free to Enjoy the Happy in Life :)'
